# Production overrides for docker-compose
services:
  standup-bot:
    # Production-specific settings
    restart: always
    
    # Health check to ensure the bot is running
    healthcheck:
      test: ["CMD", "pgrep", "node"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    # Additional security options
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
